### ISSUE TITLE
Display settings

### ISSUE THREAD

**Issue by Nezz** [theneweinstein/pysomneo#13]
My wake up light has two display settings in the app:
- Display always on
- Display brightness

Would it be possible to control these? I'd like enable always on during the day, but disable it during the night from Home Assistant.

**Comment by Frank071** [comment]
These probably are ```brght``` (brightness) and ```dspon``` (true = always on) from the ```wusts``` call

**Comment by Nezz** [comment]
Thanks for adding support @theneweinstein. I gave it a try in home assistant. I noticed that when setting both the brightness and always on from the same automation, the first setting gets lost. Example:

```
  - service: number.set_value
    metadata: {}
    data:
      value: "1"
    target:
      entity_id: number.somneo_display_brightness
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.somneo_display_always_on
```

When the brightness is initially set to a different value, running this automation results in the newly set brightness being set for a split second, which gets reverted back to the initial setting by the always on switch.

Adding a two second delay between the two calls fixes the issue.
